### ISSUE TITLE
Missing contributors in list of contributors (API)

### ISSUE THREAD

**Issue by kaitoAckerman** [SiG-FSTM/sig-fstm.github.io#10]
We should have 6 contributors show up. 
![screenshot from 2018-05-07 08-49-56](https://user-images.githubusercontent.com/13991988/39680473-a6b60764-51d3-11e8-8820-e49b61619714.png)

But [api](https://api.github.com/repos/SiG-FSTM/sig-fstm.github.io/contributors) only show 5 of them.

same as here
![screenshot from 2018-05-07 08-51-30](https://user-images.githubusercontent.com/13991988/39680497-dfdf8bdc-51d3-11e8-8c89-01735929b47b.png)

**Comment by kaitoAckerman** [comment]
I guess it just needs more time to get new data is it ? take note for the future

**Comment by AreRex14** [comment]
Oh, good to see it is solved
