### ISSUE TITLE
Theme - Change to new, better theme?

### ISSUE THREAD

**Issue by AreRex14** [SiG-FSTM/sig-fstm.github.io#23]
I think existing theme is too dull... I'm no good at creating from scratch so [webjeda cards](http://jekyllthemes.org/themes/webjeda-cards/) might be a good theme to try...can customize it a little to better suited up. You think??

**Comment by kaitoAckerman** [comment]
Hermm, really no one can lead and do this from scratch ? Html & css/scss.

**Comment by IceM4nn** [comment]
I don't like it. What customization could you make upon this theme?

**Comment by AreRex14** [comment]
> Hermm, really no one can lead and do this from scratch ? Html & css/scss.

Maybe we'll find someone in next meetup session after intro to git and github...

**Comment by AreRex14** [comment]
> 
> 
> I don't like it. What customization could you make upon this theme?

Just suggesting...I don't know, just it looks a lot better, customize it to look darker and still retains the style. But fine if don want it

**Comment by IceM4nn** [comment]
I suggest you and your team conduct a SiG session, try coding template themes for the website from scratch or do what ever you want. If its good, we'll merging your new theme with current website. you can use dev branch or contact me if you need a new repo. We'll handle that for you. Closing the issue. reopen if needed.
